### ISSUE TITLE
接口请求异常，请稍后再试！

### ISSUE THREAD

**Issue by cayden** [elunez/openai-java#1]
有遇到这个问题吗？
retrofit2.adapter.rxjava2.HttpException: HTTP 503 Service Temporarily Unavailable
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)

然后提示：接口请求异常，请稍后再试！

**Comment by elunez** [comment]
ChatGpt 官方服务器出现问题了

**Comment by cayden** [comment]
> 



> ChatGpt 官方服务器出现问题了

好的 感谢哈！
