### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by zhuxindong** [elunez/openai-java#7]
![image](https://user-images.githubusercontent.com/24989246/222356072-d4defe46-e365-4ecb-bc7d-fa731d03f304.png)
 

- 有新窗口开始监听:8081793be9db-4c42-83d6-171628572e38,当前在线人数为:1
java.lang.RuntimeException: 请求ChatGPT官方服务出错，请稍后再试
        at com.ydyno.service.impl.OpenAiServiceImpl.textQuiz(OpenAiServiceImpl.java:177)
        at com.ydyno.service.impl.OpenAiServiceImpl.communicate(OpenAiServiceImpl.java:101)
        at com.ydyno.service.WebSocketServer.onMessage(WebSocketServer.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:104)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:415)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:750)
java.lang.RuntimeException: 请求ChatGPT官方服务出错，请稍后再试
        at com.ydyno.service.impl.OpenAiServiceImpl.textQuiz(OpenAiServiceImpl.java:177)
        at com.ydyno.service.impl.OpenAiServiceImpl.communicate(OpenAiServiceImpl.java:101)
        at com.ydyno.service.WebSocketServer.onMessage(WebSocketServer.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:104)
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:415)
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:750)
openai- 2023-03-02 07:06:55 [http-nio-18080-exec-8] INFO  o.a.coyote.http11.Http11Processor - Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x000xee0x010x000x000xea0x030x030xb70xa90xf80xcdI0x8b0x030x0bjA0x8ewq0xc9*J0x05c;0x0c0x1a0xc90x7f<0x9d0x8e0x910x820xbb0xf60x15r ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:750)

**Comment by elunez** [comment]
> ![image](https://user-images.githubusercontent.com/24989246/222356072-d4defe46-e365-4ecb-bc7d-fa731d03f304.png)
> 
> * 有新窗口开始监听:8081793be9db-4c42-83d6-171628572e38,当前在线人数为:1
>   java.lang.RuntimeException: 请求ChatGPT官方服务出错，请稍后再试
>   at com.ydyno.service.impl.OpenAiServiceImpl.textQuiz(OpenAiServiceImpl.java:177)
>   at com.ydyno.service.impl.OpenAiServiceImpl.communicate(OpenAiServiceImpl.java:101)
>   at com.ydyno.service.WebSocketServer.onMessage(WebSocketServer.java:90)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:104)
>   at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:415)
>   at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
>   at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
>   at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
>   at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
>   at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
>   at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
>   at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
>   at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
>   at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
>   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
>   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
>   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
>   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
>   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
>   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>   at java.lang.Thread.run(Thread.java:750)
>   java.lang.RuntimeException: 请求ChatGPT官方服务出错，请稍后再试
>   at com.ydyno.service.impl.OpenAiServiceImpl.textQuiz(OpenAiServiceImpl.java:177)
>   at com.ydyno.service.impl.OpenAiServiceImpl.communicate(OpenAiServiceImpl.java:101)
>   at com.ydyno.service.WebSocketServer.onMessage(WebSocketServer.java:90)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:104)
>   at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:415)
>   at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:129)
>   at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:515)
>   at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:301)
>   at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
>   at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
>   at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:183)
>   at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:162)
>   at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:157)
>   at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
>   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
>   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
>   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
>   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
>   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
>   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>   at java.lang.Thread.run(Thread.java:750)
>   openai- 2023-03-02 07:06:55 [http-nio-18080-exec-8] INFO  o.a.coyote.http11.Http11Processor - Error parsing HTTP request header
>   Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
>   java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x000xee0x010x000x000xea0x030x030xb70xa90xf80xcdI0x8b0x030x0bjA0x8ewq0xc9*J0x05c;0x0c0x1a0xc90x7f<0x9d0x8e0x910x820xbb0xf60x15r ]. HTTP method names must be tokens
>   at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419)
>   at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271)
>   at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
>   at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
>   at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
>   at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>   at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
>   at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
>   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>   at java.lang.Thread.run(Thread.java:750)

不好意思，  这个参数忘记提交上去了，已经更新了
```bash
# 综合问答API，gpt-3.5模型
  openai_api: https://api.openai.com/v1/chat/completions
```
